### ISSUE TITLE
expect functionality only works when subprocess is flushing

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/delegator.py#1]
This annoys the hell out of me, because Python doesn't flush `stdout` when printing by default. 

Currently, interactive Python scripts must be run with `-u` to work correctly.

**Comment by char101** [comment]
Or set `PYTHONUNBUFFERED=1` in delegator.py?

**Comment by kennethreitz** [comment]
That's a good idea!

**Comment by char101** [comment]
Wouldn't setting `PYTHONUNBUFFERED` in delegator.py affects the module that imports it? Maybe it is safer to specify it via the `env` parameter when calling subprocess.

**Comment by kennethreitz** [comment]
it would not, as that code is executed by python before the interpreter gets to where i'm setting it. it will only effect other subprocesses.

**Comment by char101** [comment]
Not in stdout buffering, but there are other cases that it may affect the program execution:

1. if the module checks for `PYTHONUNBUFFERED` in `os.environ`
2. other python process that is spawned by the main module
