### ISSUE TITLE
command with long output hangs forever

### ISSUE THREAD

**Issue by wong2** [kennethreitz/delegator.py#14]
How to reproduce:

```
>>> import delegator
>>> delegator.run("sh -c 'for((i=1; i<=100000; i++)); do echo $i; done'").out
```

this will hang forever

**Comment by shaded-enmity** [comment]
Related issue: https://github.com/kennethreitz/pipenv/issues/303

The way blocking command are currently handled is definitely a bug (block() -> wait() without giving the callee a change to read() on the pipe will always deadlock for subprocesses that write more than the kernel pipe buffer)

**Comment by kennethreitz** [comment]
how do we fix this?
