### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by drtkn** [kennethreitz/delegator.py#17]
Hi,   I am trying to get standard out from running `/usr/bin/stat` with the delegator and I am met with 
```UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 8: ordinal not in range(128)```

I did `c.out.encode('utf-8')` and see this:

  ```File: \xe2\x80\x98/\xe2\x80\x99\n  Size: 4096      \tBlocks: 8          IO Block: 4096   director .... ``

I further found the following line is responsible for the error: 
`result += self.subprocess.read().decode('utf-8')`

Thank you.

**Comment by nateprewitt** [comment]
This is being addressed in #21.

**Comment by nateprewitt** [comment]
Resolved with eadc479.
