### ISSUE TITLE
CWD option(s) to set the current working directory for command?

### ISSUE THREAD

**Issue by hvisage** [kennethreitz/delegator.py#29]
Goodday,

 I don't see that delegator allows me to specify the directory that the command(s) must executed in, thus I was wondering how to set that in delegator?

 I have the case/need where I'll be running from a Flask application with a far removed (directory wise) Ansible scripts that needs to be executed.

**Comment by JasonBristol** [comment]
I submitted PR #41 to hopefully add this, I as well had a use case for this

**Comment by justinmayer** [comment]
Since @kennethreitz just merged the aforementioned PR, this issue can be closed.

(P.S.: A new release containing this and other recent changes would be most welcome. ☺️)
