### ISSUE TITLE
module 'delegator' has no attribute 'run'

### ISSUE THREAD

**Issue by epogrebnyak** [kennethreitz/delegator.py#30]
I'm on windows, installed *delegator* with pip and try running it with code below:

```python
import delegator 
c = delegator.run("python -v")
```
getting error:
```
  File "C:/Users/EP/Documents/GitHub/todo-core/test_guz.py", line 8, in <module>
    c = delegator.run("python -v")

AttributeError: module 'delegator' has no attribute 'run'
```

what is possibly wrong?

**Comment by nateprewitt** [comment]
Hey @epogrebnyak, did you install delegator or delegator.py with Pip? It's important to note these are two separate packages and "delegator" is not this project.

If you did install "delegator.py" and are still experiencing this issue, I'd suggest verifying you don't have another file named "delegator.py" on your path. That's the only other reason you should be experiencing issues.

**Comment by epogrebnyak** [comment]
You are right , I needed to do ```pip install delegator.py```, plain *delegator* is indeed a separate package.
Thank you for quick and prcise response, @nateprewitt !
