### ISSUE TITLE
what is the difference for capturing "dir" and "python -V" commands?

### ISSUE THREAD

**Issue by epogrebnyak** [kennethreitz/delegator.py#31]
I'm expermenting with delegator.py on Windows, trying to capture process output  (whatever was printed to console). 

Apparently, I can capture output of a console command, like this:

```python
import delegator
c = delegator.run('dir c:') 
assert c.out.startswith(' Volume in drive C is')
```
However, when trying to capture output of ```python -V``` command, I get empty string while somehting like ```'Python 3.6.0'``` is expected:

```python
d = delegator.run('python -V') 
# expected 'Python 3.6.0'
assert d.out == ''
```

**Comment by kennethreitz** [comment]
Python is printing that to standard error, i believe.

**Comment by epogrebnyak** [comment]
Indeed - this thing passes well:

```
d = delegator.run('python -V') 
assert d.err.startswith('Python')
```

Thank you!
