### ISSUE TITLE
Can I run a command in shell?

### ISSUE THREAD

**Issue by Xuanwo** [kennethreitz/delegator.py#4]
It looks like not support `delegator.run("my_command", shell=True)`.

**Comment by global** [comment]
From the code, this option doesn't exist. Only block=true/false is allowed. What are you trying to achieve?

**Comment by Xuanwo** [comment]
I want to run a command in a shell so that it can follow my $PATH and so on.

**Comment by markph0204** [comment]
@azillion can you also update the README as well?

**Comment by kennethreitz** [comment]
shell=True is default now
