### ISSUE TITLE
module 'delegator' has no attribute 'chain'

### ISSUE THREAD

**Issue by babvin** [kennethreitz/delegator.py#70]
import delegator

c = delegator.chain('ls | grep a')
c.out

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-076112a964a9> in <module>
      1 import delegator
----> 2 c = delegator.chain('ls | grep a')
AttributeError: module 'delegator' has no attribute 'chain'

**Comment by tvytlx** [comment]
`pip install delegator.py`

make sure the package name you install is `delegator.py`

**Comment by timofurrer** [comment]
I'm closing this issue, for the reason @tvytlx already mentioned :) 🎉

**Comment by babvin** [comment]
Still not working...

![2019-03-07 08_30_44-buster - vmware workstation](https://user-images.githubusercontent.com/30034691/53929360-7fdca100-40b3-11e9-8a97-a23724e3ffdd.png)
![2019-03-07 08_30_23-buster - vmware workstation](https://user-images.githubusercontent.com/30034691/53929361-7fdca100-40b3-11e9-8e60-8f642b5ac4c9.png)

**Comment by tvytlx** [comment]
can you run this in your jupyter and see what outputs?
```
!pip freeze | grep delegator
```

**Comment by babvin** [comment]
> !pip freeze | grep delegator

![2019-03-07 09_17_46-jupyterlab](https://user-images.githubusercontent.com/30034691/53931130-f67c9d00-40b9-11e9-9621-683624c0cad4.png)
