### ISSUE TITLE
how to pipe string to rest of commands

### ISSUE THREAD

**Issue by adriansev** [kennethreitz/delegator.py#72]
Hi! I would like to simplify my usage of subprocess and so i found your work. It would seem that it does what is advertised to do (just trying to say that is an amazing project) but documentation is a bit lacking ... i do not find a way to pipe a string to a custom chain (something like `echo stdout_from_other_process | chain_of_shell_commands_that_will_run_in_my_pseudo_terminal`).  Could someone give me a hint about it? :)   
Thank you!!

**Comment by timofurrer** [comment]
Have you tried using `delegator.chain()` yet?

```python
import delegator
c = delegator.chain("fortune | cowsay")
print(c.out)
```

**Comment by adriansev** [comment]
my question is how can i pass a string to the chain? in reference to your example, assume that the output of fortune is already obtained in a string object .. how can i pass this string to `| cowsay` ?

**Comment by timofurrer** [comment]
A Python string?

If so:

```python
string = "Hello World"
c = delegator.chain(f"{string} | cowsay")
```

**Comment by adriansev** [comment]
Thanks a lot!!! i did not thought about this!!! One more question : if the string contains single and double quotes, is there a need to escape them? The scenario is where the usage is of the type :    
string1 = "message received from a websocket"      
string2 = "arbitrary shell command received from user input that could contain other |"      
c = delegator.chain(f"echo '{string1}' | echo '{string2}' ")      
Thanks a lot for help!

**Comment by timofurrer** [comment]
Well, besides the security risks you are facing there you would have to escape single quotes yourself for `string1`. Maybe something in https://docs.python.org/3/library/shlex.html helps you to escape.

**Comment by adriansev** [comment]
wow! thanks a lot for your help and info!!
