### ISSUE TITLE
Only first argument is used

### ISSUE THREAD

**Issue by jonmcclung** [kennethreitz/delegator.py#74]
I just did `pip3 install delegator.py` and I cannot get multiple arguments to work. As an example:

```python
import delegator

# as a single argument works fine
delegator.run(['echo hello']).out
# outputs: 'hello\n'

# as multiple arguments seems to only use the first one
delegator.run(['echo', 'hello']).out
# outputs: '\n', expected output: 'hello\n'
```

**Comment by tmbull** [comment]
I experienced the same...

**Comment by frostming** [comment]
Delegator.run passes `shell=True` flag to `Popen`, which doesn't accept a list of command.

**Comment by xrobin** [comment]
This looks like #58.

Note that the readme file says you can pass a list of commands  

    Commands can be passed in as lists as well (e.g. ``['ls', '-lrt']``), for parameterization.

So the closing reason seems a bit out of place.
