### ISSUE TITLE
Version 0.0.6 not in master branch & setup.py still says version='0.0.5'

### ISSUE THREAD

**Issue by hexchain** [kennethreitz/delegator.py#8]
In the "releases" page there is version 0.0.6, but it's missing from the master branch, it only exists as a tag. And the setup.py of the 0.0.6 tarball still says `version='0.0.5'`.

**Comment by kennethreitz** [comment]
fixed!

**Comment by hexchain** [comment]
Unfortunately there's a missing tag of v0.0.7 this time...

**Comment by kennethreitz** [comment]
@hexchain patience is a virtue

**Comment by hexchain** [comment]
Oh, thank you!
